server:
  port: 8085

spring:
  application:
    name: notification-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: coditas@123
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME}
    password: ${MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

clients:
  auth-service-url: http://localhost:8081

nestly:
  mail:
    from: ${MAIL_USERNAME}

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
