server:
  port: 8081

spring:
  application:
    name: auth-service
  datasource:
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: coditas@123
  jpa:
    hibernate:
      ddl-auto: update

clients:
  notification-service-url: http://localhost:8085


app:
  jwt:
  access-token-expiration: 900000 #15 min
  refresh-token-expiration: 604800000 # 7 days

nestly:
  jwt:
    secret: change-me-nestly-dev-secret-key-32chars-min!
  seed-admin-email: omlakade8@gmail.com
  s3:
    region: ap-south-1
    access-key: test
    secret-key: test
    bucket: nestly-docs
    endpoint: ""

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
