server:
  port: 8084

spring:
  application:
    name: application-service
  datasource:
    url: jdbc:postgresql://localhost:5432/nestly_application
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: update

clients:
  listing-service-url: http://localhost:8082
  notification-service-url: http://localhost:8085

nestly:
  s3:
    region: ap-south-1
    access-key: test
    secret-key: test
    bucket: nestly-docs
    endpoint: ""

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
