"""Created the Properties , PropertyMedia and VerificationReport

Revision ID: 249095ae09aa
Revises: 
Create Date: 2026-07-15 09:35:53.727850

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '249095ae09aa'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('properties_table',
    sa.Column('owner_id', sa.UUID(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=False),
    sa.Column('location', sa.String(), nullable=False),
    sa.Column('rent_amount', sa.Integer(), nullable=False),
    sa.Column('amenities', sa.String(), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'REJECTED', 'CHANGES_NEEDED', name='property_status'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_properties_table_location'), 'properties_table', ['location'], unique=False)
    op.create_index(op.f('ix_properties_table_owner_id'), 'properties_table', ['owner_id'], unique=False)
    op.create_index(op.f('ix_properties_table_status'), 'properties_table', ['status'], unique=False)
    op.create_table('property_media_table',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('file_url', sa.String(), nullable=False),
    sa.Column('media_type', sa.Enum('PHOTO', 'OWNERSHIP_DOC', name='mediatype'), nullable=False),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_property_media_table_property_id'), 'property_media_table', ['property_id'], unique=False)
    op.create_table('verification_reports_table',
    sa.Column('property_id', sa.UUID(), nullable=False),
    sa.Column('completeness', sa.JSON(), nullable=True),
    sa.Column('consistency', sa.JSON(), nullable=True),
    sa.Column('pricing', sa.JSON(), nullable=True),
    sa.Column('red_flags', sa.JSON(), nullable=True),
    sa.Column('summary', sa.String(), nullable=True),
    sa.Column('key_concerns', sa.JSON(), nullable=True),
    sa.Column('recommendation', sa.String(), nullable=True),
    sa.Column('status', sa.Enum('IN_PROGRESS', 'COMPLETED', name='reportstatus'), nullable=True),
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['property_id'], ['properties_table.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_verification_reports_table_property_id'), 'verification_reports_table', ['property_id'], unique=False)
    op.create_index(op.f('ix_verification_reports_table_status'), 'verification_reports_table', ['status'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_verification_reports_table_status'), table_name='verification_reports_table')
    op.drop_index(op.f('ix_verification_reports_table_property_id'), table_name='verification_reports_table')
    op.drop_table('verification_reports_table')
    op.drop_index(op.f('ix_property_media_table_property_id'), table_name='property_media_table')
    op.drop_table('property_media_table')
    op.drop_index(op.f('ix_properties_table_status'), table_name='properties_table')
    op.drop_index(op.f('ix_properties_table_owner_id'), table_name='properties_table')
    op.drop_index(op.f('ix_properties_table_location'), table_name='properties_table')
    op.drop_table('properties_table')
    # ### end Alembic commands ###
