server:
  port: 8080

spring:
  application:
    name: api-gateway

  cloud:
    gateway:
      globalcors:
        corsConfigurations:
          "[/**]":
            allowedOriginPatterns:
              - "*"
            allowedMethods:
              - "*"
            allowedHeaders:
              - "*"
            allowCredentials: true

      routes:
        - id: auth-service-docs
          uri: ${nestly.services.auth}
          predicates:
            - Path=/docs/auth/v3/api-docs
          filters:
            - RewritePath=/docs/auth/v3/api-docs, /v3/api-docs

        - id: notification-service-docs
          uri: ${nestly.services.notification}
          predicates:
            - Path=/docs/notification/v3/api-docs
          filters:
            - RewritePath=/docs/notification/v3/api-docs, /v3/api-docs

        - id: auth-service
          uri: ${nestly.services.auth}
          predicates:
            - Path=/auth/**,/users/**

        - id: notification-service
          uri: ${nestly.services.notification}
          predicates:
            - Path=/notifications/**,/internal/**

nestly:
  jwt:
    secret: change-me-nestly-dev-secret-key-32chars-min!
  services:
    auth: http://localhost:8081
    notification: http://localhost:8085

springdoc:
  swagger-ui:
    path: /swagger-ui.html
    urls:
      - name: Auth Service
        url: /docs/auth/v3/api-docs
      - name: Notification Service
        url: /docs/notification/v3/api-docs

  api-docs:
    enabled: false